### ISSUE TITLE
Please separate the streaming services.

### ISSUE THREAD

**Issue by CHJ85** [RW1986/IPTV#1]
Hi there. Do you think you could devide these into separate m3u files so I can use their EPGs?
Now that everything's merged into the same playlist it's impossible to build an EPG that works with all of them.

**Comment by RW1986** [comment]
I could separate them, but I'm not sure what you mean by building an EPG that works with all of them? I have a merged EPG in the readme that combines all the EPG data for each service to work alongside the m3u file, is this not what you're looking for?
