### ISSUE TITLE
Guide 

### ISSUE THREAD

**Issue by MrC001** [RW1986/IPTV#2]
Not working.

**Comment by RW1986** [comment]
Could I please have some more information? Is the whole guide not working for you, or just some of it? What device and software are you using to view the guide data?

I have just tried it on TiviMate via Android and it worked fine, except for one or two channels which I'll take a look at.

**Comment by RW1986** [comment]
This issue will be closed in 48 hours if no new information is provided. Thank you.

**Comment by MrC001** [comment]
Seems better now.....
